poetry の導入
furukawa-laboratory/somf pull request #151
Opened 2020-05-24 08:08 UTC by shmokmt

** Description 説明 **
通りすがりの岡本と申します。機械学習に知見のない自分でも貢献できそうなpoeryのissueがありましたので、PRを差し上げます。

Close #126 

* poetry をプロジェクトに導入しました。
* プロダクションコードから必要なサードパーティのライブラリを洗い出して追加しました。

Close #126 

** Type of change 変更の種類**

Please delete options that are not relevant for your post.
関係のないオプションは削除してください

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

2020-05-24 08:11 UTC, shmokmt reviewed
補足コメントを追加しました。

2020-05-24 08:11 UTC, shmokmt commented on pyproject.toml
> +name = "somf"
実際にpypiにpublishする際はsomfディレクトリを読みに行くと思うので、その際は
#84 をクローズする必要があるかと思います。

2020-05-24 08:11 UTC, shmokmt commented on pyproject.toml
> +scipy = "^1.4.1"
runtimeは以下のバージョンで導入しました。
不都合がある場合は教えて下さい。

2020-05-24 08:12 UTC, shmokmt commented
@ae14watanabe  レビューをお願いいたします 🙏

2020-05-24 08:36 UTC, ae14watanabe commented
@shmokmt ありがとうございます！研究室外からのプルリクエストは初なので本当にありがたいです！後ほどレビューさせて頂きます！

2020-06-17 12:35 UTC, shmokmt commented
@ae14watanabe こちらレビュー状況いかがでしょうか？ 👀

2020-06-17 13:31 UTC, ae14watanabe commented
お待たせしてすみません！やっと自分のローカル環境でpoetryが使えるようになったので今週中にreviewしたいと思います〜！

2020-06-21 07:21 UTC, ae14watanabe requested changes
自分の環境のバージョンをsuggestionしましたので反映してもらえると助かります！

2020-06-21 07:21 UTC, ae14watanabe commented on pyproject.toml
> +tensorflow = "^2.2.0"
```suggestion
```

2020-06-21 07:21 UTC, ae14watanabe commented on pyproject.toml
> +sklearn = "^0.0"
```suggestion
sklearn = "^0.22.1"
```

2020-06-21 07:21 UTC, ae14watanabe commented on pyproject.toml
> +scipy = "^1.4.1"
どのバージョンなら動くかとかあまり詳しく調べていないのですが，とりあえず自分の環境のバージョンを入れさせてもらいました！こうやって書くんだなと勉強になりました．ありがとうございます！

2020-06-21 07:21 UTC, ae14watanabe commented on pyproject.toml
> +
```suggestion
matplotlib = "^2.2.2<3.0"
```

2020-06-21 07:21 UTC, ae14watanabe commented on pyproject.toml
> +
2.2.2以上で3.0未満ってこの書き方で表現できてますかね…？

2020-06-21 07:58 UTC, shmokmt commented on pyproject.toml
> +tensorflow = "^2.2.0"
こちら新しいバージョンのsuggestion漏れでしょうか？ 👀

2020-06-21 07:58 UTC, shmokmt commented on pyproject.toml
> +
poetryは前のバージョンのprefixの記号(Caret requirements)でどこまでのバージョンを許容するか決まります。`^2.2.2` と記載した時点で 3.0.0へ自動的に更新されないようになるので、
`matplotlib = "^2.2.2"` で良さそうです。
https://python-poetry.org/docs/versions/

2020-06-21 08:10 UTC, ae14watanabe commented on pyproject.toml
> +
なるほどそうなんですね！勉強になります！

2020-06-21 08:12 UTC, ae14watanabe commented on pyproject.toml
> +tensorflow = "^2.2.0"
説明不足でした！とりあえずtensorflowは含めなくて大丈夫です！tensorflow依存のモデルはあとでライブラリから除く予定なので！

2020-06-21 08:19 UTC, shmokmt commented on pyproject.toml
> +tensorflow = "^2.2.0"
承知しました 🙆‍♂️

2020-06-21 08:24 UTC, shmokmt reviewed
pyproject.tomlを反映した後にlockファイルを生成する必要があり、suggestionをコミットするだけでマージできそうにないので、一旦ローカルで指摘いただいた箇所を反映します。

2020-06-21 08:24 UTC, shmokmt commented on pyproject.toml
> +name = "somf"
いまここで package nameを somf にしちゃうと、poetry isntall 時にパッケージがインストールされなくなり
`/tests`、`/tutorials/` からの`libs` import が全て失敗してしまうので、`libs` に変更します。
追々、パッケージ名を整えるフェーズに入ったら変えてもらえればと思います 🙏

2020-06-21 08:28 UTC, ae14watanabe commented
承知しました！ありがとうございます〜泣

2020-06-21 08:39 UTC, shmokmt commented
動作確認のために1ファイルだけテストコード走らせました。

```sh
.venv ❯ python tests/som/allclose_somkl/allclose_somklishida_vs_somkl_watanabe.py
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 1752.80it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 1609.32it/s]
.
----------------------------------------------------------------------
Ran 1 test in 0.251s

OK
```

2020-06-21 08:41 UTC, shmokmt commented on pyproject.toml
> +sklearn = "^0.0"
scikit-learnのpip名は`sklearn`とてっきり思っていたのですが、こちらは野良の関係ないライブラリでした... https://pypi.org/project/sklearn/
正しくは `scikit-learn` だったのでそちらでバージョン合わせました。
https://scikit-learn.org/stable/install.html

2020-06-21 08:44 UTC, shmokmt commented
@ae14watanabe 指摘いただいた箇所を修正しました。もう1度レビューお願いします 🙏

2020-06-23 02:56 UTC, ae14watanabe commented
@shmokmt ありがとうございます！現在自分がちょっとpoetry周りでトラブルが起きておりまして，レビューもうしばらくお待ちください！

2020-07-16 09:08 UTC, ae14watanabe commented
@shmokmt お久しぶりです！対応遅くなっていて大変申し訳ないのですが，ブランチがこちらから見えなくなっていまして，これってどういう原因が考えられるのでしょうか…？汗
![image](https://user-images.githubusercontent.com/19607449/87652528-4cbe1d80-c78f-11ea-8e33-13762cc190d9.png)

2020-07-16 09:29 UTC, shmokmt commented
@ae14watanabe 
すみません、先日誤ってforkしたレポジトリを私が消してしまったのが原因のようです。
PRを後日作り直そうと思います 💦

2020-07-16 10:10 UTC, ae14watanabe commented
あらそうでしたか汗
お手数おかけします

2021-01-01 04:47 UTC, TetraMiyazaki commented
すみません．今更確認してます．unknown repositoryってなってるの初めてみました．file changesは残っているのでどうにかならないのかな

2025-06-11 09:04 UTC, closed without merging